@startuml

autonumber

participant "main" as m
participant "perso : Perso" as p
participant "laby : Labyrinthe" as l

activate m

m -> p : getX()
activate p
m <-- p : x

m -> p : getY()
m <-- p : y
deactivate p

m -> l : getSuivant(x, y, "GAUCHE")
activate l
m <-- l : [x,y]
m -> l : getMur(x, y)
m <-- l : boolean

alt si getMur renvoie false
m -> l : deplacerPerso("GAUCHE")
m <-- l : void
end



@enduml