@startuml

autonumber

participant "main" as m
participant "monstre : Monstre" as monstre
participant "laby : Labyrinthe" as l

activate m

m -> monstre : getX()
activate monstre
m <-- monstre : x

m -> monstre : getY()
m <-- monstre : y
deactivate monstre

m -> l : getSuivant(x, y, "GAUCHE")
activate l
m <-- l : [x,y]
m -> l : deplacementValide(x, y)
m <-- l : boolean

alt si deplacementValide renvoie true

m -> l : deplacerEntite(e, "GAUCHE")

l -> monstre : deplacer(suiv)
activate monstre

l <-- monstre : void
deactivate monstre

m <-- l : void
end



@enduml