@startuml

autonumber

participant "laby : Labyrinthe" as l
participant "perso : Perso" as p

participant "main" as m
participant "perso : Perso" as p
participant "laby : Labyrinthe" as l

activate m

m -> p : getX()
activate p
m <-- p : x
deactivate p

m -> p : getY()
activate p
m <-- p : y
deactivate p

m -> l : getSuivant(x, y, action)
activate l
m <-- l : [x,y]
deactivate l
m -> l : deplacementValide(x, y)
activate l
m <-- l : boolean

alt si deplacementValide renvoie true
    m -> l : deplacerEntite(perso,action)
    m <-- l : void
end

deactivate l
deactivate m

@enduml