@startuml
package gameLaby.laby{
class Labyrinthe{
+ <static final> MUR: char
+ <static final> PJ: char
+ <static final> VIDE: char
+ <static final> HAUT: String
+ <static final> BAS: String
+ <static final> GAUCHE: String
+ <static final> DROITE: String
+ <static final> MONSTRE : char
+ <static final> ESCALIERUP : char
+ <static final> ESCALIERDOWN : char
+ murs : boolean[][]
+ Labyrinthe(String nom)
+ getSuivant(int x, int y, String action) : int[]
+ deplacerPerso(String action)
+ deplacerEntitee()
+ etreFini(): boolean
+ getLengthY(): int
+ getLength(): int
+ getMur(int x, int y): boolean
+ getEntites()

}
class Perso{
+Perso(int dx, int dy)
}
Abstract class Entitée{
- x : int
- y : int
+ etrePresent(int dx, int dy): boolean
+setX()
+setY()
+getX(): int
+getY(): int
+{abstract}deplacer()
}
class Monstre{
+deplacer()
}
class Escalier{

}
}
Labyrinthe "1" --> "*" Entitée : monstres
Labyrinthe "1" --> "1" Perso : + pj
Entitée <|-- Monstre
Entitée <|-- Perso
Entitée <|-- Escalier
@enduml