@startuml
title Changer d'étage


participant "main" as m
participant "labydessin : LabyDessin" as labyd
participant "labyJeu : LabyJeu" as labyj
participant "laby : Labyrinthe" as labyrinthe
participant "entités : Arraylist<Entité>" as entités
participant "monstre : Monstre" as mstr
activate m
m-> labyd:DessinerJeu((Jeu jeu, Canvas canvas));
activate labyd
labyd -> labyj : getLabyrinthe()
activate labyj
labyd <-- labyj : labyrinthe
deactivate labyj
labyd -> labyrinthe: getEntités()
activate labyrinthe
labyd<-- labyrinthe: entités
deactivate labyrinthe
loop
labyd -> entités : get(i)*
activate entités
labyd <-- entités : Monstre
deactivate entités
labyd -> mstr : getX()
activate mstr
labyd <-- mstr
labyd -> mstr : getY()
labyd <-- mstr
deactivate mstr
m<-- labyd
deactivate labyd
deactivate m
end loop


@enduml