@startuml
title Changer d'étage


participant "labyJeu : LabyJeu" as labyj
participant "labyrinthe : Labyrinthe" as labyrinthe
participant "pj : Perso" as pj
participant "escalier : Escalier" as escalier


-> labyj : update(...)
activate labyj

labyj -> labyrinthe : chercherEscalier()
activate labyrinthe

labyrinthe -> pj : getX()
activate pj
labyrinthe <-- pj : x
deactivate pj

labyrinthe -> pj : getY()
activate pj
labyrinthe <-- pj : y
deactivate pj


create escalier
labyrinthe -> escalier : chercherEscalier(x, y)

labyj -> labyj : changerLabyCourant(suivant)





@enduml