@startuml
title Changer d'étage


participant "labyJeu : LabyJeu" as labyj
participant "labyrinthe : Labyrinthe" as labyrinthe
participant  "entiteInteractives : ArrayList<EntiteInteractives>" as ei



-> labyj : update(...)
activate labyj




labyj -> labyrinthe : getX()
activate labyrinthe
labyj <-- labyrinthe : x
labyj -> labyrinthe : getY()
labyj <-- labyrinthe : y

labyj -> labyrinthe : chercherEntitéeInteractive(x, y)
loop

labyrinthe -> ei : get()i
activate ei
labyrinthe <-- ei :
deactivate ei
end loop
labyj <-- labyrinthe : res
deactivate labyrinthe




labyj -> labyj : changerLabyCourant(escalier.montant)
labyj <-- labyj
<-- labyj





@enduml